name = "NET"
uuid = "760056a9-20cf-428f-b963-ba2d9f6cbae6"
authors = ["Emre Dayanga√ß"]
version = "1.0.0-DEV"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1.10"
Plots = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
